
export const METEROTABLE_REQUEST = "METEROTABLE_REQUEST";
export const METEROTABLE_RECEIVE = "SELEMETEROTABLE_RECEIVE";
export const METEROTABLE_FAILURE = "METEROTABLE_FAILURE";
export const RESET_METEROTABLE = "RESET_METEROTABLE";

