
export const REVIEWSUBMISSION_REQUEST = "REVIEWSUBMISSION_REQUEST";
export const REVIEWSUBMISSION_RECEIVE = "SELEREVIEWSUBMISSION_RECEIVE";
export const REVIEWSUBMISSION_FAILURE = "REVIEWSUBMISSION_FAILURE";
export const RESET_METEROTABLE = "RESET_METEROTABLE";

