export const GETJOB_REQUEST = "SELECTJOB_REQUEST";
export const GETJOB_RECEIVE = "SELECTJOB_RECEIVE";
export const GETJOB_FAILURE = "SELECTJOB_FAILURE";
export const RESET_GETJOB = "RESET_SELECTJOB";

